### ISSUE TITLE
Payment options do not show on checkout

### ISSUE THREAD

**Issue by lerygit** [ICEPAY/Magento-2#7]
Hi,

I installed the module on magento 2.1.8 and have sync (and enabled) the payment methods. But i still dont see any options on the checkout page.

**Comment by WebWeave** [comment]
@tsygankov could you look at this issue again?

**Comment by Justin991q** [comment]
I have the same issue as well on Magento 2.2

**Comment by tsygankov** [comment]
Hi guys,

Thanks for reporting the issue. I will check on this and get back with you soon.

**Comment by tsygankov** [comment]
I reproduced the problem, now working on the bugfix

**Comment by tsygankov** [comment]
Still in progress

**Comment by Justin991q** [comment]
Alright, thanks for the update.

**Comment by tsygankov** [comment]
Hi guys,

The problem is fixed in 70127f9e5c14ee7cc4dda7d939e298eeb001e0fd. We still need to check if there are any other Magneto 2.2.x compatibility issues.

**Comment by Frankhendriks** [comment]
hello,

i installed latest version: "version": "1.0.1-beta4",
in a clean magento 2.2.3 , and this issue is still there, i tried the fix provided in https://github.com/ICEPAY/Magento-2/commit/70127f9e5c14ee7cc4dda7d939e298eeb001e0fd

there were indeed differences in these files, but even after updating changes to the file checkout_index_index.xml 
the problem is still there.

i had this exact same problem in a magento 2.1.11 installation and after updating the checkout_index_index.xml i did fix the issue in that installation.

**Comment by NataljaCig** [comment]
Hi Frankhendriks, 
Please use version 1.1.0. The source code is available in the master branch. 

You can install the latest version of the module via composer. 

Add ICEPAY Payment Module repository to composer: 

`composer config repositories.icepay git https://github.com/ICEPAY/Magento-2.git `

Install the module: 

`composer require icepay/icepay-magento2-module:dev-master `

Enable the module: 

`php bin/magento setup:upgrade`

`php bin/magento setup:static-content:deploy`

 Please do not hesitate to contact us if you have any other questions. 

Customer Support

**Comment by tsygankov** [comment]
Hi guys,

Please let me know if upgrade to v1.1.0 solved the problem.

/Stan

**Comment by Frankhendriks** [comment]
@tsygankov It actually did fix it.
